### ISSUE TITLE
Are lit tests handled?

### ISSUE THREAD

**Issue by smeenai** [google/llvm-bazel#186]
This is a question and not an issue, but I was curious if this build setup handles running LLVM's lit-based tests, and if so, how their build was setup. I searched around and I see the build for the unit tests, but I couldn't find any build for the lit-style tests.

**Comment by GMNGeoffrey** [comment]
Thanks for the question :slightly_smiling_face: These build files don't currently attempt to run the lit tests. As a general meta-note, I've also been lax on updating the documentation on this repo because we're moving these build files upstream into the LLVM monorepo in a sub-community supported side-directory: https://github.com/llvm/llvm-www/blob/main/proposals/LP0002-BazelBuildConfiguration.md

To expand a bit more, the model of lit doesn't play nicely with Bazel, which wants individual test actions to be small and fine-grained. At Google, we went through various iterations and eventually ended up implementing a custom lit runner (someone much closer to this described it in https://groups.google.com/g/llvm-dev/c/ysh1GvGbHgs/m/crfQYG_mAAAJ). In the IREE project, we currently have a hacky shell script that we use (https://github.com/google/iree/blob/main/iree/tools/run_lit.sh) with an accompanying Bazel macro (https://github.com/google/iree/blob/main/iree/lit_test.bzl). This works because we use a very small subset of lit features. I believe TensorFlow just uses lit.py in single-file mode and eats the overhead (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/glob_lit_test.bzl).

For this repository, our focus has been enabling projects that use LLVM and build with Bazel, so getting lit tests working wasn't a priority. The unit tests mostly serve as a smoke test that the build system itself is working. But if someone is interested in the lit tests I think we'd be happy to accept that contribution (though I'd recommend holding off until we're actually in the LLVM monorepo). We could see how bad the single-file mode of lit.py really is for this. At least at Google internally the team using it found it untenable. Or maybe the GSoC project I linked to discussion about above will result in a lit runner that would work better for this use case :smile:

**Comment by smeenai** [comment]
Thanks for the detailed response :) Yeah, I was mostly curious how the model of lit and the model of Bazel could be reconciled. At Facebook, we use Buck as our build system (which is similar to Bazel). We build parts of LLVM with Buck already and are considering expanding that, but getting lit tests working well was one sticking point, and I was curious how others were handling that. The links are really helpful, and I'll have to dig into all of this more; thank you!
